# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate-v2]

pagination:
  enabled: true
  per_page: 3
  permalink: "/page/:num/"

comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Cere Blanco, Software Engineer
description: "Cere Blanco, Portfolio on Github"
keywords: "Cere Blanco, Software Engineer"
url: cereblanco.github.io
baseurl: ""

google_analytics: ""
repo: "https://github.com/cereblanco/cereblanco.github.io"
disqus_shortname: ""
disqus_site_shortname: ""
# Author settings
author:
  name: Cere Blanco
  job: Software Engineer
  bio: "
  I accidentally majored in Computer Science in college. <br />
  Then pursued a Masters degree in the same field. <br />
  I write software for work and for leisure! <br />
  I like beaches and plants! <br />
  "
  location: Manila, Philippines
  thumb: /images/author.jpg
  email: cereblanco@gmail.com
  github: https://github.com/cereblanco
  twitter: https://twitter.com/cereblanco
  linkedin: https://linkedin.com/in/mssblanco

# navbar pages
# navbar:
#   - slug: Blog
#     title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
